### ISSUE TITLE
would you please provide a wiki document about these config files?

### ISSUE THREAD

**Issue by sggggy** [Crivaledaz/Mattermost-LDAP#1]
ldap_config.php
resource.php
connexion.php

needs config samples,thank you.

**Comment by Crivaledaz** [comment]
Hi,

I am implementing a Puppet module for Mattermost-LDAP and I will probably push it next week. This puppet module will come with a more detailed document on configurations files. I am sorry for the delay, if you have specific questions about these files, feel free to ask, I will try to help you.

Below there is a short description of configuration parameters : 

#### In oauth/LDAP/config_ldap.php
* $hostname : Your LDAP hostname or LDAP IP, to connect to the LDAP server.
* $port : Your LDAP port, to connect to the LDAP server. By default : 389.	

#### In oauth/connexion.php
* $rdn : The LDAP Relative Directory Name to identify a user in LDAP, see LDAP.php class for more information (use to check user credentials on LDAP). 

Refers to ldap_bind() in php documentation.

#### In oauth/resource.php
* $base : The base directory name of your LDAP server. (ex : ou=People,o=Company)
* $filter : Additional filters for your LDAP, see LDAP.php class for more information (used to get user informations) 

Refers to ldap_search() and ldap_get_entries() in php documentation.

To find these information see  /etc/openldap/ldap.conf (for openldap) or try to use ldapsearch from openldap package (I never use other ldap :/)

Regards,
