### ISSUE TITLE
isbug

### ISSUE THREAD

**Issue by paddy235** [Crivaledaz/Mattermost-LDAP#11]
fedora 389 ldap
config_ldap.php:
```
$hostname = "ldap://ldap.abb.app:10389";

$port = 10389;
```
LDAP.php:
```
    public function __construct($hostname, $port = 389)
    {
        if (!is_string($hostname)) 
        {
            throw new InvalidArgumentException('First argument to LDAP must be the hostname of a ldap server (string). Ex: ldap//example.com/ ');
        }
        
        if (!is_int($port)) 
        {
            throw new InvalidArgumentException('Second argument to LDAP must be the ldap server port (int). Ex : 389');
        }

        $ldap = ldap_connect($hostname)
        	or die("Unable to connect to the ldap server : $ldaphost ! Please check your configuration.");

```

if is $ldap = ldap_connect($hostname,$port) then fail ldap_bind(): Unable to bind to server: Can't contact LDAP server

**Comment by Crivaledaz** [comment]
Hi,

In fact, this is an error, the line should be $ldap = ldap_connect($hostname,$port), else the $port argument is useless.
However, in the php manual, there are two different ways to use ldap_connect($host,$port) : 
- host : This field supports using a hostname or, with OpenLDAP 2.x.x and later, a full LDAP URI of the form ldap://hostname:port or ldaps://hostname:port for SSL encryption.
- port : The port to connect to. Not used when using LDAP URIs.

So I suggest you to only use $hostname = "ldap://ldap.abb.app:10389"; or $hostname = "ldap://ldap.abb.app"; $port = 10389;
Note, if you use LDAP 1.x you should use the second option.

I hope this will solve your problem, keep me updated please :)

Thanks for your feedback, I will fix this point in the next commit.

Regards

**Comment by paddy235** [comment]
thank you verymatch
