### ISSUE TITLE
 ldap_search(): Search: Operations error

### ISSUE THREAD

**Issue by tsarkovan** [Crivaledaz/Mattermost-LDAP#116]
Hello community!

I'm using master branch and trying to use docker compose. Whe all containers start, i try to login in web and then i get error in log. 
php-1    | NOTICE: PHP message: PHP Warning:  ldap_search(): Search: Operations error in /var/www/html/oauth/LDAP/LDAP.php on line 118

Line 118 is: 
$result = ldap_search($this->ldap_server, $ldap_base_dn, $search_filter,array(), 0, 1, 500);

i use MS AD

**Comment by tsarkovan** [comment]
it was only in one installation

**Comment by tsarkovan** [comment]
If someone happens to encounter this, try specifying the base DN more precisely. For example, change dc=domen, dc=loc to ou=users, dc=domen, dc=loc.

**Comment by kelsen** [comment]
This is great but what if all your active users is outside of ou=users, dc=example, dc=local or scattered around multiples OUs?
