### ISSUE TITLE
Don't include config files in repository

### ISSUE THREAD

**Issue by Rudloff** [Crivaledaz/Mattermost-LDAP#13]
Hello,
Would it be possible to exclude the various config files from the repository and only provide example files (e.g. `oauth/LDAP/config_ldap.example.php`).
Right now, it is too easy to commit credentials by mistake.

**Comment by Crivaledaz** [comment]
Hi,

I have setup config files with an ".example" extension in order to take into account your proposition.
Thank you for your feedback, I'm sorry for the delay.
