### ISSUE TITLE
Uncaught exception when using a wrong username/password

### ISSUE THREAD

**Issue by Rudloff** [Crivaledaz/Mattermost-LDAP#18]
When trying to login with a wrong user, I get a blank page and this error in the logs:
```
[Mon Nov 20 16:18:48.202878 2017] [:error] [pid 22205] [client 2a01:e35:2428:cf30:88c1:81ce:5dbe:ac7e:56640] PHP Fatal error:  Uncaught exception 'Exception' with message 'An error has occured during ldap_first_entry execution. Please check parameter of LDAP/checkLogin.' in /home/tools/Mattermost-LDAP/oauth/LDAP/LDAP.php:126\nStack trace:\n#0 /home/tools/Mattermost-LDAP/oauth/connexion.php(43): LDAP->checkLogin('foobarbaz', 'foobarbaz', 'uid', 'objectClass=per...', 'ou=People,dc=an...', 'cn=mattermost_l...', '****')\n#1 {main}\n  thrown in /home/tools/Mattermost-LDAP/oauth/LDAP/LDAP.php on line 126, referer: https://tools.animafac.net/mattermost-ldap/oauth/index.php
```

I guess it would better to catch the exception in order to display an error page.
(Also, credentials are displayed in logs, which is not very safe.)

**Comment by Crivaledaz** [comment]
Hi, 

In fact, this was a serious security problem, thank you for reporting. 

The new version, committed this day, catches any exception and returns an error page when credentials are wrong. Let me know if you find another security issue.

Thank you for your feedback and again sorry for the delay
