### ISSUE TITLE
MM 4.4.0, IIS and external PostgreSQL server - Bad Response from token request

### ISSUE THREAD

**Issue by mauricio-sonegatti** [Crivaledaz/Mattermost-LDAP#19]
Tried to install and run with my IIS php server and an external pgsql server, my Active Directory responded correctly, but it seems the token is not called never.
Up until the authorize.php is called, everything is fine, the table oauth_authorization_codes is filled, everything seems fine, but instead of going for the token, it falls short... 
[2017/12/05 14:33:12 UTC] [DEBG] GET - /oauth/gitlab/signup
[2017/12/05 14:33:13 UTC] [DEBG] GET - /signup/gitlab/complete
[2017/12/05 14:33:13 UTC] [EROR] AuthorizeOAuthUser: Bad response from token request, response_body=

Using Gitlab works as intended, if someone have an idea to try I'm open to it.
I already tried the #9 alterations but no dice, I think the problem lies elsewhere, maybe 4.4 calls the token differently than 4.1?

**Comment by Crivaledaz** [comment]
I close this issue since there is no update for one year. Feel free to reopen it if you still have the problem.

Regards
