### ISSUE TITLE
Something wrong in my head :)

### ISSUE THREAD

**Issue by iUkka** [Crivaledaz/Mattermost-LDAP#2]
**ADDED: It was a selinux trouble.**

setsebool -P httpd_can_network_connect 1

---

after clean install cenos7 i try to run

> [root@oauth html]# ./init_mysql.sh
> This script will create a new Oauth role and an associated database for Mattermost-LDAP
> To edit configuration please edit this script before running !
> 
> SuperUser right must be ask to create the new role and database in mysql
> 
> Press ctrl+c to stop the script
> Creation of role oauth and database ... (need to be root)
> ERROR 1007 (HY000) at line 1: Can't create database 'oauth_db'; database exists
> ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'oauth'@'%'
> Creation of tables for database (using oauth)
> ERROR 1045 (28000): Access denied for user 'oauth'@'localhost' (using password: YES)
> ERROR 1045 (28000): Access denied for user 'oauth'@'localhost' (using password: YES)
> ERROR 1045 (28000): Access denied for user 'oauth'@'localhost' (using password: YES)
> ERROR 1045 (28000): Access denied for user 'oauth'@'localhost' (using password: YES)
> ERROR 1045 (28000): Access denied for user 'oauth'@'localhost' (using password: YES)
> ERROR 1045 (28000): Access denied for user 'oauth'@'localhost' (using password: YES)
> Insert new client in the database
> ERROR 1045 (28000): Access denied for user 'oauth'@'localhost' (using password: YES)
> ERROR 1045 (28000): Access denied for user 'oauth'@'localhost' (using password: YES)
> 

Also after dropping DB, dropping user same error

[root@oauth html]# mysql -u root --password=mattermostpassword --execute "DROP USER oauth;"
[root@oauth html]# mysql -u root --password=mattermostpassword --execute "DROP DATABASE oauth_db;"

> [root@oauth html]# ./init_mysql.sh
> This script will create a new Oauth role and an associated database for Mattermost-LDAP
> To edit configuration please edit this script before running !
> 
> SuperUser right must be ask to create the new role and database in mysql
> 
> Press ctrl+c to stop the script
> Creation of role oauth and database ... (need to be root)
> Creation of tables for database (using oauth)
> ERROR 1045 (28000): Access denied for user 'oauth'@'localhost' (using password: YES)
> ERROR 1045 (28000): Access denied for user 'oauth'@'localhost' (using password: YES)
> ERROR 1045 (28000): Access denied for user 'oauth'@'localhost' (using password: YES)
> ERROR 1045 (28000): Access denied for user 'oauth'@'localhost' (using password: YES)
> ERROR 1045 (28000): Access denied for user 'oauth'@'localhost' (using password: YES)
> ERROR 1045 (28000): Access denied for user 'oauth'@'localhost' (using password: YES)
> Insert new client in the database
> ERROR 1045 (28000): Access denied for user 'oauth'@'localhost' (using password: YES)
> ERROR 1045 (28000): Access denied for user 'oauth'@'localhost' (using password: YES)
> Client has been created ! Oauth Database is configured.
> 

config is
> oauth_user="oauth"
> oauth_db_name="oauth_db"
> oauth_pass="mattermostpassword"

Installed only 
sudo yum -y --nogpgcheck install httpd php mariadb-server mariadb php-ldap php-pdo php-mysql git

**Comment by sggggy** [comment]
search keyword 'mysql_pass',the first one needs the mysql root password
