### ISSUE TITLE
Improve design

### ISSUE THREAD

**Issue by mickael-kerjean** [Crivaledaz/Mattermost-LDAP#22]
Hi there,

Congrats for shipping `:)`. I'm about to deploy an instance but the current version does't have any CSS which makes it feel rough around the edges. Would you accept a pull request to fix this?

**Comment by Crivaledaz** [comment]
Hi,

Yes, if you want, you can suggest a CSS design for the Oauth web pages.

I just have a requirement : could you attach any element (images, bootstrap ...) in the project, or provide a support for deployment in system with no internet connection (or through a proxy). Some companies, like mine, have a restricted access to internet from inside and this will be nice the design does not impact accessibility in this case.

Moreover, you should be aware about the project license, I do not want to use proprietary images or whatever.

Thank you for your help, I am glad you contribute to the project :)

Regards,

Crivaledaz

**Comment by mickael-kerjean** [comment]
I'm closing this as I don't see myself putting this code in production
