### ISSUE TITLE
Invalid State Token

### ISSUE THREAD

**Issue by benyaa** [Crivaledaz/Mattermost-LDAP#27]
Hi,
I'm trying to use it with Mattermost 5.8.0 and I'm having a problem.. After fully configuring Mattermost-LDAP and I press 'authorize', it redirect me to '{mattermost}/signup/gitlab/complete', then it fails with 500 error. When I refresh the page, it returns an error "Invalid state token". 

What could be the problem?

**Comment by patrickober** [comment]
You should carefully read through this existing issue -> https://github.com/Crivaledaz/Mattermost-LDAP/issues/5#issuecomment-323246369 
As you don't provide any errorlog there is not much to guess about the error you ran into. 
It could be a misconfigured webserver, or misconfigured mattermost or even a misconfigured Mattermost-LDAP setup.
Though i can tell you Mattermost 5.8.0 works fine for my setup (nginx -> mattermost, nginx -> apache(php) -> oauth).

**Comment by benyaa** [comment]
Actually, eventually I've solved it.
I've commented row 38 (`$resp = array("id" =>.....`) and removed the comment from row 41(`$resp = array("name" => ......`).
Seems like it's not only consistent with Mattemost before version 4.4 but with 5.8.0 too. 
I'll close it then.
