### ISSUE TITLE
Typo in readme?

### ISSUE THREAD

**Issue by iUkka** [Crivaledaz/Mattermost-LDAP#3]
#For PostgreSQL
sudo yum -y --nogpgcheck install httpd php postgresql-server postgresql php-ldap php-pdo php-psql git

may be 
#For PostgreSQL
sudo yum -y --nogpgcheck install httpd php postgresql-server postgresql php-ldap php-pdo **php-pgsql** git

**Comment by Crivaledaz** [comment]
Hi,

Thanks you for your remark. Actually, this is a typo, the good packet name is **php-pgsql**. 
I have planned to update the readme next week (certainly Wednesday). If you remarks other error, or if you have any other suggestion feel free to comment this issue.

Regards,
