### ISSUE TITLE
404 error after activating Enterprise Edition

### ISSUE THREAD

**Issue by Aladiah2** [Crivaledaz/Mattermost-LDAP#39]
After activating Enterprise Edition from Team Edition the login form (not the GitLab-Button) doesn't appear anymore.
The link unter the GitLab button seems to be right, but after click I get an 404 error and this line in my brower:
https://<Servername>/oauth/resource.php/oauth/authorize?response_type=code&client_id=<LongId>&redirect_uri=https%3A%2F%2F<Servername>%2Fsignup%2Fgitlab%2Fcomplete&state=<VeryLongId>
The prefs in the backend are the same and oauth-GitLab is activ.

access log: Compared to the Team Edition I don't see "POST /oauth/connexion.php".
After this line I see the same line in both editions: "GET /oauth/authorize.php?response_type=code&client_id....".

We want to migrate smoothly and needing the GitLab-AD Extension until all users are migrated.
Thank you.

**Comment by Crivaledaz** [comment]
Hi,

Thanks you for your interest in my project Mattermost-LDAP.

Honestly, I have never tried Mattermost Enterprise Edition, that's the reason why I have built this module. I don't know if there are differences on the Gitlab connector between Mattermost Team Edition and Enterprise Edition, but if Gitlab authentifictaion is supported by both edition, my module should work.

Can you check if the Oauth configuration in the Gitlab settings of Mattermost has not been modified by the migration to Enterprise edition ?

Usually, when you click on the Gitlab button, your are redirected to the authorize page on the Oauth server (`GET /oauth/authorize.php?response_type=code&client_id=XXX&redirect_uri=https://<oauth>/signup/gitlab/complete&state=XXX`). If you are not logged in already, you are redirected to the login form at `index.php` (via POST). When you click connect on the login form, you are sent to the `connexion.php` page which try to authenticate you against LDAP server. If your credentials are valid, you are redirected again to the `authorize.php` page to authorize Mattermost to get your informations. After that, Mattermost directly connect Oauth  server on the `token.php` page to get your information. So, if you don't reach the login form, there is no POST request, this is expected.

I am sorry for this late answer, let me know if you still have the problem,

Regards,

**Comment by Aladiah2** [comment]
Hi,

thank you for the answer.

Last weekend we did a bulk migration from "gitlab" to "ldap", but before I 
remarked that your Extension was working well in Enterprise!
Would have been an issue from out testserver before. Sorry!

Regards,
Ulf


"Denis CLAVIER" <notifications@github.com> schrieb am 31.03.2020 11:30:34:

> Von: "Denis CLAVIER" <notifications@github.com>
> An: "Crivaledaz/Mattermost-LDAP" <Mattermost-LDAP@noreply.github.com>
> Kopie: "Aladiah2" <aladiah@mucker.info>, "Author" 
<author@noreply.github.com>
> Datum: 31.03.2020 11:30
> Betreff: Re: [Crivaledaz/Mattermost-LDAP] 404 error after activating
> Enterprise Edition (#39)
> 
> Hi,
> Thanks you for your interest in my project Mattermost-LDAP.
> Honestly, I have never tried Mattermost Enterprise Edition, that's 
> the reason why I have built this module. I don't know if there are 
> differences on the Gitlab connector between Mattermost Team Edition 
> and Enterprise Edition, but if Gitlab authentifictaion is supported 
> by both edition, my module should work.
> Can you check if the Oauth configuration in the Gitlab settings of 
> Mattermost has not been modified by the migration to Enterprise edition 
?
> Usually, when you click on the Gitlab button, your are redirected to
> the authorize page on the Oauth server (GET /oauth/authorize.php?
> response_type=code&client_id=XXX&redirect_uri=https://<oauth>/
> signup/gitlab/complete&state=XXX). If you are not logged in already,
> you are redirected to the login form at index.php (via POST). When 
> you click connect on the login form, you are sent to the connexion.php
> page which try to authenticate you against LDAP server. If your 
> credentials are valid, you are redirected again to the authorize.php
> page to authorize Mattermost to get your informations. After that, 
> Mattermost directly connect Oauth server on the token.php page to 
> get your information. So, if you don't reach the login form, there 
> is no POST request, this is expected.
> I am sorry for this late answer, let me know if you still have the 
problem,

**Comment by Crivaledaz** [comment]
Thank you for the feedback. I close this issue. Feel free to reopen it if needed.
