### ISSUE TITLE
Trouble in config

### ISSUE THREAD

**Issue by iUkka** [Crivaledaz/Mattermost-LDAP#4]
Sorry, but i am no knowledge in php.

on Centos7

> ldapsearch -x -h vdc.example.local -D "bot@example.local" -W -b "ou=EXAMPLE,dc=example,dc=local" -s sub "(cn=*)" cn mail

Works like charm.

my LDA/config.ldap.php
` <?php
$hostname = "ldap://vdc.examle.local/";
$port = 389;`

In oauth/resource.php
`$base = "ou=EXAMPLE,dc=example,dc=local";
$filter = "uid=" . $uid;`

oauth/connexion.php
`        $rdn = 'uid=' . $user . 'ou=EXAMPLE,dc=example,dn=local';`
and also try
`         $rdn = 'uid=' . $user . '@examle.local';`
or
`        $rdn = 'uid=' . $user . '';
` 

i also added (for test): 
> echo "Authetification failed ... Login is $rdn password is $password";

login and password is correct.

I always recieve auth failed.
I down know how debug my fault :)

**Comment by Crivaledaz** [comment]
Hello,

You will find in attachment a PHP file designed to test the LDAP bridge with PHP. This script directly uses the php-ldap library. Be sure that you have installed packages : php-ldap and php (5.3 minimum)

Can you try to run this script and give me feedback, please. I hope this script will solve your problem.

Besides, verify that php-ldap is activated and associated with php. See your php info file (just write `<?php phpinfo();` in a new file and access it with your internet browser.) You must have an LDAP section. Sometimes restart httpd solved some LDAP issues.

I'm waiting for your feedback, good luck,

Crivaledaz
[ldap.php.zip](https://github.com/Crivaledaz/Mattermost-LDAP/files/1227909/ldap.php.zip)

**Comment by iUkka** [comment]
Thank you!

After some test  i changed line
> $dn = "bot@example.local";

and they probably works:

> [root@oauth LDAP]# php LDAP.php
> <h3>LDAP : Test Center</h3>Attempting to connect LDAP server ... <br />Successful connection ! <br />Checking LDAP credentials ... <br />Successful authentication ! <br />Getting user informations ...<br />Data recovered with success ! <br />Extracting useful data : <br /><br />Closing LDAP connection.
> 
>

**Comment by iUkka** [comment]
Added:

I returned old LDAP.php, modified alittle
replaced line
//$rdn = 'uid=' . $user . '@cironline.ru';
to
$rdn = $user . '@example.local';

and recieve something good :)
![image](https://user-images.githubusercontent.com/5823637/29362031-d6a124ec-8292-11e7-86f7-1c9a7fe5c267.png)


Thank you alot!
