### ISSUE TITLE
Authorize/Deny question page comes again and again (decision not stored)

### ISSUE THREAD

**Issue by b3** [Crivaledaz/Mattermost-LDAP#45]
As stated in #43, once I logged into the system with Mattermost-LDAP, every time I want to log in I get the *Authorize/Deny* page as if the first answer was not saved.

Is it a feature or a bug?

Maybe linked to #44 too.

**Comment by Crivaledaz** [comment]
This one is more a bug, or a missing feature. I agree with you, the user's decision could be stored, to avoid mattermost-LDAP to always ask the permission.

I think I could check if the user already exists on the `users` table and disable the authorize question in this case. The best would be a check box to allow users to choose if they want Oauth to remember their decision, but this need to add a field in the database, and this has some consequences on backward compatibility.

Something more to add on my TODO list, do not hesitate to make a pull request if you want to help :)

**Comment by Crivaledaz** [comment]
Hi,

I finally found some time during the lockdown, and I have worked on a new Mattermost-LDAP version. So, I am glad to announce Mattermost-LDAP V2 is now in beta :) 

This new version includes new features to bring solutions to #44 and #45. You can try it from the branch [v2](https://github.com/Crivaledaz/Mattermost-LDAP/tree/v2). For more informations about this version, see the [changelog file](https://github.com/Crivaledaz/Mattermost-LDAP/blob/v2/changelog.md)

Please, let me know if this new version solves your issues.

Regards

**Comment by grvsmth** [comment]
I tested v2, and it seems to be working.  I am no longer being asked to authorize every time.  Thanks, Denis!

**Comment by b3** [comment]
Unfortunately we switch to using an empty gitlab for authentication (which is using LDAP). It is not perfect but it runs and is in production now.
We thus wont be able to test the new version of Mattermost-LDAP before some (long) time.

Thank's however for the nice work.

**Comment by Crivaledaz** [comment]
I close this issue since this feature has been added in Mattermost-LDAP V2.

**Note** : The authorization is granted for an unlimited time. The Oauth server asks for authorization only if user does not exist in the `users` table, and add the user to this table after the first authorization is granted.
