### ISSUE TITLE
Wrong variable in init_mysql.sh

### ISSUE THREAD

**Issue by agabellini** [Crivaledaz/Mattermost-LDAP#59]
Hello,

in init_mysql.sh file there is **$db_name_name** variable instead of **$db_name**

Andrea

**Comment by Crivaledaz** [comment]
Hi,

Thank you for reporting that typo. I corrected that in the commit [122e713](https://github.com/Crivaledaz/Mattermost-LDAP/commit/122e7138e7de7c5941f7c243e0319a9223b09d6c).

I close this issue, thank you for your contribution to Mattermost-LDAP.

Regards
