### ISSUE TITLE
Clarification in HOSTNAME for mattermost-ldap

### ISSUE THREAD

**Issue by promehul** [Crivaledaz/Mattermost-LDAP#60]
![Screenshot from 2020-07-09 13-32-09](https://user-images.githubusercontent.com/32803738/87013711-b2873400-c1e8-11ea-8cfa-ddd8b6754b89.png)

Hello everyone. 
I am employing the docker-compose approach. I already have my existing mattermost-server and webapp on host "https://flipchat.southindia.cloudapp.azure.com/" which is a VM. I now wanna enable ldap. SInce ldap would have a container of its own, its not clear which HOSTNAME to use in the mentioned field.
Any help would be appreciated

**Comment by alexanderjackson** [comment]
You need to add the hostname which resolves to the machine on which you are running the docker containers.

**Comment by promehul** [comment]
That means this "https://flipchat.southindia.cloudapp.azure.com"..

**Comment by alexanderjackson** [comment]
If you are running the docker container on the same host, then yes.
